### ISSUE TITLE
当前版本 jprotobuf.version 过旧

### ISSUE THREAD

**Issue by nnnggel** [baidu/Jprotobuf-rpc-socket#47]
当前版本 jprotobuf.version（jhunters/jprotobuf） 使用的版本：
`<jprotobuf.version>1.10.2</jprotobuf.version>`

ProtobufProxy.doCreate 中 
`long lastModify = ClassHelper.getLastModifyTime(cls); `
代码过早（在缓存 CACHED 判断前）的调用赋值，导致几乎每次进入 doCreate 方法都会被调用，而该行代码非常耗cpu。

该问题在 1.10.5 中已经修复，能否升级：
https://github.com/jhunters/jprotobuf/releases/tag/jprotobuf-1.10.5

**Comment by jhunters** [comment]
会尽快升级，对应修正版本为 3.5.8. 发布后会回复

**Comment by jhunters** [comment]
已发布

**Comment by nnnggel** [comment]
[赞]
