### ISSUE TITLE
无效端口判断应该是小于最小，大于最大吧

### ISSUE THREAD

**Issue by feiadan** [baidu/Jprotobuf-rpc-socket#54]
https://github.com/baidu/Jprotobuf-rpc-socket/blob/e84f36301ef97a73c9b8e41aa2a00773e7f32fe6/jprotobuf-rpc-core/src/main/java/com/baidu/jprotobuf/pbrpc/utils/NetUtils.java#L126-L134

**Comment by xiemalin** [comment]
该问题是一个bug, 会在下一个版本修复，感谢反馈

**Comment by xiemalin** [comment]
已修复  版本 3.5.19

**Comment by xiemalin** [comment]
https://github.com/baidu/Jprotobuf-rpc-socket/blob/e84f36301ef97a73c9b8e41aa2a00773e7f32fe6/jprotobuf-rpc-core/src/main/java/com/baidu/jprotobuf/pbrpc/utils/NetUtils.java#L126-L134
